import { atom } from 'recoil';

// 누구랑 함께 키워드
export const withCategoryState = atom({
  key: 'withCategoryState',
  default: 0,
});

// 테마 키워드
export const themeCategoryState = atom({
  key: 'themeCategoryState',
  default: [],
});

// 성별 키워드
export const genderCategoryState = atom({
  key: 'genderCategoryState',
  default: 0,
});

// 연령 키워드
export const ageCategoryState = atom({
  key: 'ageCategoryState',
  default: 0,
});

// 코스 더미 데이터
export const courseDummyState = atom({
  key: 'courseDummyState',
  default: [
    {
      COURSE_ID: 1,
      MEMBER_ID: 30,
      TITLE: '더 현대 서울점 카페 투어',
      CONTENT: '더 현대 서울의 여러 카페를 돌아다니며 다양한 커피와 디저트를 맛볼 예정입니다.',
      START_TIME: '2024-04-01 18:04:14',
      END_TIME: '2024-04-01 16:48:27',
      WITH_WHOM: '혼자',
      THEME: '쇼핑 홀릭',
      VISIBILITY: 'N',
    },
    {
      COURSE_ID: 2,
      MEMBER_ID: 25,
      TITLE: '더 현대 서울에서 쇼핑하기',
      CONTENT: '더 현대 서울에서 친구와 함께 다양한 매장을 구경하고 쇼핑할 예정입니다.',
      START_TIME: '2024-04-01 15:35:08',
      END_TIME: '2024-04-01 17:11:59',
      WITH_WHOM: '연인',
      THEME: 'SNS 핫플레이스',
      VISIBILITY: 'N',
    },
    {
      COURSE_ID: 3,
      MEMBER_ID: 14,
      TITLE: '현대 서울에서 하루 보내기',
      CONTENT: '현대 서울점에서 다양한 활동을 즐기며 하루를 보낼 예정입니다.',
      START_TIME: '2024-04-01 17:52:33',
      END_TIME: '2024-04-01 15:00:06',
      WITH_WHOM: '연인',
      THEME: 'SNS 핫플레이스',
      VISIBILITY: 'N',
    },
    {
      COURSE_ID: 4,
      MEMBER_ID: 21,
      TITLE: '현대 서울 탐방',
      CONTENT: '현대 서울의 매장을 둘러보고 다양한 카페에서 시간을 보낼 예정입니다.',
      START_TIME: '2024-04-01 17:52:10',
      END_TIME: '2024-04-01 15:57:07',
      WITH_WHOM: '아이',
      THEME: '쇼핑 홀릭',
      VISIBILITY: 'N',
    },
    {
      COURSE_ID: 5,
      MEMBER_ID: 25,
      TITLE: '현대 서울에서 힐링하기',
      CONTENT: '연인과 함께 현대 서울의 맛집을 탐방하고 힐링 시간을 가질 예정입니다.',
      START_TIME: '2024-04-01 15:32:55',
      END_TIME: '2024-04-01 14:30:26',
      WITH_WHOM: '아이',
      THEME: '맛집 탐방',
      VISIBILITY: 'N',
    },
    {
      COURSE_ID: 6,
      MEMBER_ID: 17,
      TITLE: '현대 서울에서 보내는 하루',
      CONTENT: '현대 서울점에서 쇼핑과 맛집 탐방을 하며 하루를 보낼 예정입니다.',
      START_TIME: '2024-04-01 11:05:30',
      END_TIME: '2024-04-01 16:20:45',
      WITH_WHOM: '친구',
      THEME: '쇼핑 홀릭',
      VISIBILITY: 'Y',
    },
    {
      COURSE_ID: 7,
      MEMBER_ID: 9,
      TITLE: '현대 서울점 나들이',
      CONTENT: '현대 서울점에서 가족과 함께 다양한 활동을 즐길 예정입니다.',
      START_TIME: '2024-04-01 14:10:25',
      END_TIME: '2024-04-01 18:45:30',
      WITH_WHOM: '부모님',
      THEME: '도심 속 힐링',
      VISIBILITY: 'Y',
    },
    {
      COURSE_ID: 8,
      MEMBER_ID: 3,
      TITLE: '현대 서울점 데이트',
      CONTENT: '연인과 함께 현대 서울에서 데이트를 즐길 예정입니다.',
      START_TIME: '2024-04-01 12:30:40',
      END_TIME: '2024-04-01 17:30:55',
      WITH_WHOM: '연인',
      THEME: 'SNS 핫플레이스',
      VISIBILITY: 'Y',
    },
    {
      COURSE_ID: 9,
      MEMBER_ID: 28,
      TITLE: '현대 서울 탐방',
      CONTENT: '혼자서 현대 서울의 다양한 매장을 둘러보고 힐링 시간을 가질 예정입니다.',
      START_TIME: '2024-04-01 11:15:50',
      END_TIME: '2024-04-01 14:45:10',
      WITH_WHOM: '혼자',
      THEME: '도심 속 힐링',
      VISIBILITY: 'N',
    },
    {
      COURSE_ID: 10,
      MEMBER_ID: 5,
      TITLE: '현대 서울점에서의 하루',
      CONTENT: '아이와 함께 현대 서울에서 쇼핑과 놀이를 즐길 예정입니다.',
      START_TIME: '2024-04-01 13:00:00',
      END_TIME: '2024-04-01 19:00:00',
      WITH_WHOM: '아이',
      THEME: '쇼핑 홀릭',
      VISIBILITY: 'Y',
    },
    {
      COURSE_ID: 11,
      MEMBER_ID: 12,
      TITLE: '현대 서울점 투어',
      CONTENT: '부모님과 함께 현대 서울점에서 쇼핑과 맛집을 탐방할 예정입니다.',
      START_TIME: '2024-04-01 12:00:10',
      END_TIME: '2024-04-01 17:10:50',
      WITH_WHOM: '부모님',
      THEME: '맛집 탐방',
      VISIBILITY: 'N',
    },
    {
      COURSE_ID: 12,
      MEMBER_ID: 7,
      TITLE: '현대 서울에서의 힐링',
      CONTENT: '현대 서울점에서 친구와 함께 힐링하며 시간을 보낼 예정입니다.',
      START_TIME: '2024-04-01 15:00:00',
      END_TIME: '2024-04-01 18:00:00',
      WITH_WHOM: '친구',
      THEME: '도심 속 힐링',
      VISIBILITY: 'Y',
    },
    {
      COURSE_ID: 13,
      MEMBER_ID: 20,
      TITLE: '현대 서울에서 맛집 탐방',
      CONTENT: '혼자서 현대 서울의 다양한 맛집을 탐방하며 시간을 보낼 예정입니다.',
      START_TIME: '2024-04-01 11:30:20',
      END_TIME: '2024-04-01 14:30:45',
      WITH_WHOM: '혼자',
      THEME: '맛집 탐방',
      VISIBILITY: 'N',
    },
    {
      COURSE_ID: 14,
      MEMBER_ID: 2,
      TITLE: '현대 서울점 나들이',
      CONTENT: '아이와 함께 현대 서울점에서 다양한 놀이와 쇼핑을 즐길 예정입니다.',
      START_TIME: '2024-04-01 13:45:10',
      END_TIME: '2024-04-01 17:45:20',
      WITH_WHOM: '아이',
      THEME: '쇼핑 홀릭',
      VISIBILITY: 'Y',
    },
    {
      COURSE_ID: 15,
      MEMBER_ID: 10,
      TITLE: '현대 서울에서 데이트',
      CONTENT: '연인과 함께 현대 서울에서 다양한 맛집과 카페를 즐길 예정입니다.',
      START_TIME: '2024-04-01 12:20:30',
      END_TIME: '2024-04-01 16:50:40',
      WITH_WHOM: '연인',
      THEME: '맛집 탐방',
      VISIBILITY: 'N',
    },
  ],
});
